netopeer2 with new libnetconf2 API
CESNET/netopeer2 pull request #1469
Opened 2023-09-14 08:36 UTC by Roytak

Initial changes for netopeer2 in order to use new libnetconf2 API.

Some of the most notable changes include:
- removal of configuration callbacks, it's handled by ln2
- removal of some redundant command line opts
- removal of some np2's YANG modules, they are loaded via ln2's schema dir
- the SSH and TLS options have been merged into one, that is SSH_TLS

2023-09-14 09:44 UTC, michalvasko requested changes

2023-09-14 09:44 UTC, michalvasko commented on tests/np_test.c
>          /* exec server listening on a unix socket */
There is a UNIX socket but not set up here so adjust the comment.

2023-10-06 13:57 UTC, michalvasko requested changes

2023-10-06 13:57 UTC, michalvasko commented on scripts/common.sh
> +	if [ -n "$SYSREPOCTL_EXECUTABLE" ]; then
Indent.

2023-10-06 13:57 UTC, michalvasko commented on scripts/merge_config.sh
> +    echo "Creating user \"${CURRENT_USER}\" that can authenticate with a key pair from his authorized_keys..."
The message (and the one below) is a bit inaccurate, the user is not being created, only added into the server configuration.

2023-10-06 13:57 UTC, michalvasko commented on scripts/remove.sh
>  # {% raw %} - jinja2 command to not process "{#" in the script
This can be removed, obsolete now. At the script end, too.

2023-10-06 13:57 UTC, michalvasko commented on src/netconf_server.c
> +np2srv_pubkey_auth_cb(const struct nc_session *session, ssh_key key, void *UNUSED(user_data))
Server (libnetconf2) should use the authorized keys configured for the client, not read them from the system or am I missing something?

2023-10-06 13:57 UTC, michalvasko commented on tests/np_test.c
> +    if (unsetenv("LN2_MODULE_DIR")) {
Missing unset for `NP2_SCRIPTS_DIR`.

2023-10-11 07:52 UTC, Roytak commented
Figured there is no need for the files `netconf_server.c` and `netconf_server.h` if there's only one function definition (the libnetconf2 callback) in them, so removed them.

2023-10-11 08:22 UTC, michalvasko approved these changes

2023-10-11 08:24 UTC, merged