Add option for setting PID
CESNET/netopeer2 pull request #764
Opened 2020-11-19 15:23 UTC by syyyr

Hi, now that there options for separating the sysrepo repository and shm prefix via environmental variables, the only thing that disallows launching more netopeer2 processes is the pidfile. This PR adds on option to set a custom pid file.

2020-11-19 16:07 UTC, jktjkt approved these changes
And just to clarify, the reason for running several `netopeer2-server` processes in the first place is automated unit tests of NETCONF-talking software -- the [`netconf-cli`](https://github.com/CESNET/netconf-cli) in our case. It is very convenient just to launch `netopeer2-server` and react to sysrepo callbacks from the test suite.

2020-11-20 13:29 UTC, michalvasko requested changes
Generally seems fine, thanks.

2020-11-20 13:29 UTC, michalvasko commented on src/main.c
> +    const char* pidfile = NP2SRV_PID_FILE_PATH;
Minor formatting problem, use `char *` please.

2020-11-20 13:59 UTC, syyyr commented on src/main.c
> +    const char* pidfile = NP2SRV_PID_FILE_PATH;
done

2020-11-20 14:53 UTC, michalvasko approved these changes

2020-11-20 14:54 UTC, merged